[package]
name = "bashx"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "Sandboxed Bash provider"

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
